---
- name: Configure Hadoop HDFS DataNode
  sudo: yes
  template: src={{ item }}.xml.j2 dest={{ hdfs_conf_dir }}/{{ item | replace("datanode-", "") }}.xml
  with_items:
    - core-site
    - datanode-hdfs-site
#  notify:
#    - Restart Hadoop HDFS DataNode
  tags:
    - hdfs

- name: Spread Public Key
  authorized_key: 
    user: hdfs 
    key: "/tmp/id_dsa.pub" 
    state: present
  when: fetch_public_key
  tags:
    - hdfs

- name: Create Hadoop HDFS DataNode data directories
  sudo: yes
  file: 
    path: "/dfs/dn"
    owner: hdfs
    group: hdfs
    state: directory
  register: existing_data_directory
  tags:
    - hdfs

- name: Enable and start the Hadoop HDFS DataNode service
#  service: name=hadoop-hdfs-datanode enabled=yes state=started
  sudo_user: hdfs
  command: "hadoop-daemon.sh start datanode"
  tags:
    - hdfs
