---
- name: Create HDFS installation dir
  sudo: yes
  file: 
    path: "{{ hdfs_install_dir }}"
    owner: hdfs
    group: hdfs
    state: directory
  register: created_hdfs_install_dir
  tags:
    - hdfs

- name: Create HDFS configuration dir
  sudo: yes
  file: 
    path: "{{ hdfs_conf_dir }}"
    owner: hdfs
    group: hdfs
    state: directory
  register: created_hdfs_conf_dir
  tags:
    - hdfs

- name: Download HDFS binary
  sudo: yes
  get_url:
    url: "http://apache.mirrors.pair.com/hadoop/common/hadoop-{{ hdfs_version }}/hadoop-{{ hdfs_version }}.tar.gz" 
    dest: /tmp/hadoop-{{ hdfs_version }}.tar.gz
  tags:
    - hdfs

- name: Setup HDFS binary
  sudo_user: hdfs
  unarchive: 
    src: /tmp/hadoop-{{ hdfs_version }}.tar.gz 
    dest: "{{ hdfs_install_dir }}"
    copy: no
  tags:
    - hdfs

- name: Setup HDFS environment
  sudo: yes
  template: src=hadoop.sh.j2 dest=/etc/profile.d/hadoop.sh
  tags:
    - hdfs

- include: namenode.yml
  when: hdfs_namenode 

- include: datanode.yml
  when: not hdfs_namenode 
