---
- name: install collectd
  sudo: yes
  yum:
    name: collectd
    state: present
  tags:
    - collectd

- name: create collectd config directory
  sudo: yes
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - /etc/collectd/conf.d/
    - /etc/collect.d
  tags:
    - collectd

- name: create collectd plugin directory
  sudo: yes
  file:
    path: /usr/share/collectd/plugins
    state: directory
    mode: 0755
  tags:
    - collectd

- name: configure collectd
  sudo: yes
  template:
    src: collectd.conf.j2
    dest: /etc/collectd.conf
  notify:
    - restart collectd
  tags:
    - collectd
