---
- name: Create Kafka Marathon Config
  run_once: true
  sudo: true
  template:
    src: "kafka.json.j2"
    dest: "/tmp/kafka.json"
  tags:
    - kafka-mesos

- name: Deploy Kafka scheduler to marathon
  run_once: true
  sudo: true
  command: "/usr/bin/curl -k --user {{ marathon_http_credentials }} -X POST -H \"Content-Type: application/json\" -d @kafka.json  https://{{ marathon }}:8080/v2/apps"
  register: some_variable
  args:
    chdir: /tmp
  tags:
    - kafka-mesos

- name: Change Kafka scheduler configuration
  when: "{"message":"An app with id [kafka-mesos-scheduler] already exists."}" == some_variable
  run_once: true
  sudo: true
  command: "/usr/bin/curl -k --user {{ marathon_http_credentials }} -X PUT -H \"Content-Type: application/json\" -d @kafka.json  https://{{ marathon }}:8080/v2/apps/kafka-mesos-scheduler"
  args:
    chdir: /tmp
  tags:
    - kafka-mesos

- name: Wait for Kafka scheduler
  run_once: true
  wait_for:
    host: "{{ ansible_hostname }}"
    port: 7000
    timeout: 1800
    delay: 20
  tags:
    - kafka-mesos
