---
- name: Create Kafka Marathon Config
  run_once: true
  sudo: true
  template:
    src: "kafka.json.j2"
    dest: "/tmp/kafka.json"
  tags:
    - kafka-mesos

- name: Deploy Kafka scheduler to marathon
  run_once: true
  sudo: true
  command: "/usr/bin/curl -k -s --user {{ marathon_http_credentials }} -X POST -H \"Content-Type: application/json\" -d @kafka.json  https://{{ marathon }}:8080/v2/apps"
  register: kafka_app_status
  args:
    chdir: /tmp
  tags:
    - kafka-mesos

- name: Change Kafka scheduler configuration
  when: kafka_app_status == '"{\"message\":\"An app with id [kafka-mesos-scheduler] already exists.\"}"'
  run_once: true
  sudo: true
  command: "/usr/bin/curl -k -s --user {{ marathon_http_credentials }} -X PUT -H \"Content-Type: application/json\" -d @kafka.json  https://{{ marathon }}:8080/v2/apps/kafka-mesos-scheduler"
  args:
    chdir: /tmp
  tags:
    - kafka-mesos

- name: Wait for Kafka scheduler
  run_once: true
  wait_for:
    state: started
    host: "{{ kafka_scheduler_hostname }}"
    port: 7000
    timeout: 300
    delay: 5
  tags:
    - kafka-mesos
