build:
  setup:
    image: sehqlr/mantl
    commands:
      - ssh-keygen -N '' -f ~/.ssh/id_rsa && eval `ssh-agent -s` && ssh-add ~/.ssh/id_rsa
      - ln -sf $$CI_MATRIX_ANSIBLE_FILE terraform.yml
      - ln -sf $$CI_MATRIX_TERRAFORM_FILE terraform.tf
      - echo "ansible-lint checking coming soon!"
  provision:
    image: sehqlr/mantl
    environment:
      # for local testing, fill in the cloud provider credentials here; secrets are not decrypted on local builds or PRs
      AWS_ACCESS_KEY_ID: "$$AWS_ACCESS_KEY_ID"
      AWS_SECRET_ACCESS_KEY: "$$AWS_SECRET_ACCESS_KEY"
      DIGITALOCEAN_TOKEN: "$$DIGITALOCEAN_TOKEN"
      GOOGLE_CREDENTIALS: "$$GOOGLE_CREDENTIALS"
      OS_AUTH_URL: "$$OS_AUTH_URL"
      OS_PASSWORD: "$$OS_PASSWORD"
      OS_REGION_NAME: "$$OS_REGION_NAME"
      OS_TENANT_ID: "$$OS_TENANT_ID"
      OS_TENANT_NAME: "$$OS_TENANT_NAME"
      OS_USERNAME: "$$OS_USERNAME"
      TF_VAR_build_number: $$BUILD_NUMBER
    commands:
      - testing/integration-test.sh
    when:
      event: push

matrix:
  CI_MATRIX_ANSIBLE_FILE:
    - terraform.sample.yml
  CI_MATRIX_TERRAFORM_FILE:
    - testing/aws.tf
    - testing/gce.tf
    - testing/do.tf
