build:
  image: sehqlr/mantl
  commands:
    - ssh-keygen -N '' -f ~/.ssh/id_rsa && eval $(ssh-agent) && ssh-add ~/.ssh/id_rsa
    - ./security-setup
    
publish:
  mantl-testing:
    image: sehqlr/mantl
    terraform.tfvars: "$$TFVARS"
    terraform.tf: $$CI_MATRIX_TERRAFORM_FILE
    terraform.yml: $$CI_MATRIX_ANSIBLE_FILE

matrix:
  CI_MATRIX_ANSIBLE_FILE:
    - terraform.sample.yml
  CI_MATRIX_TERRAFORM_FILE:
    - testing/aws.tf
