build:
  image: sehqlr/mantl
  commands:
    - exit 0
    
publish:
  sehqlr/mantl-testing:
    image: sehqlr/mantl-testing
    terraform.tfvars: "$$TFVARS"
    terraform.tf: $$CI_MATRIX_TERRAFORM_FILE
    terraform.yml: $$CI_MATRIX_ANSIBLE_FILE

matrix:
  CI_MATRIX_ANSIBLE_FILE:
    - terraform.sample.yml
  CI_MATRIX_TERRAFORM_FILE:
    - testing/aws.tf
