- hosts: all
  gather_facts: no
  tasks:
    - name: Install general packages
      sudo: true
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - java-1.8.0-openjdk
        - maven
        - gcc
        - gcc-c++
        - perl
        - ruby
        - git
        - emacs
        - nano
        - vim
        - screen
        - unzip
        - wget
        - tmux
        - zsh

    # Python 3.3
    - name: Install Software collection utilities package (for Python 3.3)
      sudo: true
      yum:
        name: scl-utils
        state: present

    - name: Install Python 3.3 collection repository package
      sudo: true
      yum:
        name: https://www.softwarecollections.org/en/scls/rhscl/python33/epel-7-x86_64/download/rhscl-python33-epel-7-x86_64.noarch.rpm
        state: present

    - name: Install Python 3.3 package
      sudo: true
      yum:
        name: python33
        state: present

    - name: Install Pip package
      sudo: true
      shell: "scl enable python33 \"bash -c 'easy_install pip'\""

    # Scala
    - name: Install Scala package
      sudo: true
      yum:
        name: http://downloads.typesafe.com/scala/2.11.6/scala-2.11.6.rpm
        state: present

    - name: Install SBT package
      sudo: true
      yum:
        name: http://repo.scala-sbt.org/scalasbt/sbt-native-packages/org/scala-sbt/sbt/0.13.1/sbt.rpm
        state: present

    # Mesos
    - name: Install Mesosphere repository package
      sudo: true
      yum:
        name: http://repos.mesosphere.io/el/7/noarch/RPMS/mesosphere-el-repo-7-1.noarch.rpm
        state: present

    - name: Install Mesos package
      sudo: true
      yum:
        name: mesos
        state: present

    - name: Resolve HDFS name node hostname to IP
      connection: local
      shell: ping -q -c 1 -t 1 {{ hdfs_namenode_host }} | grep PING | sed -e "s/).*//" | sed -e "s/.*(//"
      register: hdfs_namenode_ip

    - name: Add HDFS name node to /etc/hosts
      sudo: true
      lineinfile:
        dest: "/etc/hosts"
        regexp: ".+ {{ hdfs_namenode_host }}$"
        line: "{{ hdfs_namenode_ip.stdout }} {{ hdfs_namenode_host }}"
        state: present
      when: hdfs_namenode_ip.stdout != ''

    - name: Resolve Mesos leader hostname to IP
      connection: local
      shell: ping -q -c 1 -t 1 {{ mesos_leader_host }} | grep PING | sed -e "s/).*//" | sed -e "s/.*(//"
      register: mesos_leader_ip

    - name: Add Mesos leader to /etc/hosts
      sudo: true
      lineinfile:
        dest: "/etc/hosts"
        regexp: ".+ zookeeper.service.consul$"
        line: "{{ mesos_leader_ip.stdout }} zookeeper.service.consul"
        state: present
      when: mesos_leader_ip.stdout != ''

- hosts: all
  gather_facts: no
  roles:
    - {role: hdfs-standalone, hdfs_namenode: false, hdfs_datanode: false}

- hosts: all
  gather_facts: no
  roles:
    - spark
