---
# check security
- hosts: localhost
  gather_facts: no
  tasks:
    - name: check for security
      when: security_enabled is not defined or not security_enabled
      fail:
        msg: |
          Security is not enabled. Please run `security-setup` in the root
          directory and re-run this playbook with the `--extra-vars`/`-e` option
          pointing to your `security.yml` (e.g., `-e @security.yml`)

- include: openstack/provision-nova-key.yml
- include: openstack/provision-hosts.yml
- include: playbooks/upgrade-packages.yml serial=100%

- hosts: all
  roles:
    - common
    - collectd
    - logrotate
    - docker
    - dnsmasq
    - nginx
    - logstash

- hosts: control
  roles:
    - consul-template
    - {role: consul, consul_is_server: yes}

- hosts: resource
  roles:
    - consul-template
    - {role: consul, consul_is_server: no}

- include: playbooks/consul-join-wan.yml

- hosts: control
  gather_facts: no
  roles:
    - vault
    - zookeeper
    - exhibitor
    - {role: mesos, mesos_mode: leader}

- hosts: resource
  gather_facts: no
  roles:
    - {role: mesos, mesos_mode: follower}

- hosts: control
  gather_facts: no
  roles:
    - marathon
    - chronos

- hosts: resource
  gather_facts: no
  roles:
    - haproxy

- hosts: dev
  gather_facts: no
  roles:
    - dev

- include: hdfs.yml
- include: spark.yml
- include: kafka.yml
