---
- name: Restart Hadoop HDFS NameNode
  sudo: true
  sudo_user: hdfs
  shell: source /etc/profile.d/hadoop.sh; hadoop-daemon.sh stop namenode
  shell: source /etc/profile.d/hadoop.sh; hadoop-daemon.sh start namenode
  when: hdfs_namenode

- name: Restart Hadoop HDFS DataNode
  sudo: true
  sudo_user: hdfs
  shell: source /etc/profile.d/hadoop.sh; hadoop-daemon.sh stop datanode
  shell: source /etc/profile.d/hadoop.sh; hadoop-daemon.sh start datanode
  when: not hdfs_namenode
