---
- name: Wait for Kafka scheduler 
  run_once: true
  wait_for: 
    host: "{{ ansible_hostname }}"
    port: 7000 
    delay: 10
    timeout: 300
  tags:
    - kafka

- name: Add Kafka brockers  
  run_once: true
  sudo: true
  command: "./kafka-mesos.sh add 0..2 --heap 1024 --mem 2048 --api http://{{ ansible_hostname }}:7000"
  args:
    chdir: "{{ kafka_install_dir }}"
  tags:
    - kafka

- name: Start Kafka brockers  
  run_once: true
  sudo: true
  command: "./kafka-mesos.sh start 0..2 --api http://{{ ansible_hostname }}:7000"
  args:
    chdir: "{{ kafka_install_dir }}"
  tags:
    - kafka
