---
- name: Install git package
  sudo: true
  yum:
    name: git
    state: present
  tags:
    - kafka

- name: Download kafka-mesos repo 
  sudo: true
  git: 
    repo: "{{ kafka_mesos_repo }}" 
    dest: "{{ kafka_mesos_install_dir }}"
    force: yes
  tags:
    - kafka

- name: Build kafka-mesos project 
  sudo: true
  command: "./gradlew jar"
  args:
    chdir: "{{ kafka_mesos_install_dir }}"
    creates: "{{ kafka_mesos_install_dir }}/.gradle"
  tags:
    - kafka

- name: Download Kafka binary
  sudo: true 
  get_url: 
    url: "{{ kafka_binary_url }}/{{ kafka_version }}/kafka_{{ kafka_scala_version }}-{{ kafka_version }}.tgz"
    dest: "{{ kafka_mesos_install_dir }}"
  register: kafka_downloaded
  tags:
    - kafka 

- name: Create Kafka directory
  sudo: true
  file: 
    path: "{{ kafka_install_dir }}"
    owner: "{{ ansible_user_id }}"
    state: directory
  tags:
    - kafka

- name: Setup Kafka binary
  unarchive:
    src: "{{ kafka_mesos_install_dir }}/kafka_{{ kafka_scala_version }}-{{ kafka_version }}.tgz"
    dest: "{{ kafka_install_dir }}"
    copy: no
  tags:
    - kafka

- include: scheduler.yml
  when: kafka_downloaded | changed

- include: client.yml
  when: kafka_downloaded | changed

- include: config.yml
