---
- name: Install Java package
  sudo: true
  yum:
    name: java-1.8.0-openjdk
    state: present
  tags:
    - kafka

- name: Download Kafka binary
  sudo: true 
  get_url: 
    url: "{{ kafka_binary_url }}/{{ kafka_version }}/kafka_{{ kafka_scala_version }}-{{ kafka_version }}.tgz"
    dest: /tmp
  register: kafka_downloaded
  tags:
    - kafka 

- name: Create Kafka directory
  sudo: true
  file: 
    path: "{{ kafka_install_dir }}"
    owner: "{{ ansible_user_id }}"
    state: directory
  tags:
    - kafka

- name: Setup Kafka binary
  unarchive:
    src: /tmp/kafka_{{ kafka_scala_version }}-{{ kafka_version }}.tgz
    dest: "{{ kafka_install_dir }}"
    copy: no
  tags:
    - kafka

- include: config.yml
