---
- name: install mesos packages
  sudo: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - protobuf-devel
    - https://bintray.com/artifact/download/asteris/testing/mesos-0.26.0-2.x86_64.rpm
    - cyrus-sasl-md5
  tags:
    - mesos
    - bootstrap

- name: ensure consul.d is present
  sudo: yes
  file:
    path: "{{ consul_dir }}"
    state: directory
  tags:
    - mesos

- include: leader.yml
  when: mesos_mode == "leader" or mesos_mode == "mixed"

- include: follower.yml
  when: mesos_mode == "follower" or mesos_mode == "mixed"
