---
- name: Setup Spark binary
  sudo: true
  unarchive:
    src: /tmp/spark-{{ spark_version }}-bin-hadoop2.6.tgz  
    dest: "{{ spark_client_dir }}" 
    copy: no
  tags:
    - spark

- name: Setup Spark environment
  sudo: true
  template: src=spark.sh.j2 dest=/etc/profile.d/spark.sh
  tags:
    - spark
