---
- name: Install Mesosphere repository package
  sudo: true
  yum:
    name: http://repos.mesosphere.io/el/7/noarch/RPMS/mesosphere-el-repo-7-1.noarch.rpm
    state: present
  tags:
    - spark

- name: Install Mesos package
  sudo: true
  yum:
    name: mesos
    state: present
  tags:
    - spark

- name: Unarchive Spark binaries
  sudo: true
  unarchive:
    src: "{{ spark_install_dir }}/{{ item }}.tgz"
    dest: "{{ spark_install_dir }}"
    copy: no
  with_items: spark_packages
  tags:
    - spark

- name: Create Spark configurations
  sudo: true
  template:
    src: "spark-defaults.conf.j2"
    dest: "{{ spark_install_dir }}/{{ item }}/conf/spark-defaults.conf"
  with_items: spark_packages
  tags:
    - spark

- name: Create Spark environment scripts
  sudo: true
  template:
    src: "spark-env.sh.j2"
    dest: "{{ spark_install_dir }}/{{ item }}/conf/spark-env.sh"
    mode: 0775
  with_items: spark_packages
  tags:
    - spark

- name: Create symbolic link to Spark folder
  sudo: true
  file:
    src: "{{ spark_install_dir }}/{{ spark_default_package }}"
    dest: "{{ spark_install_dir }}/spark"
    state: link
  tags:
    - spark

- name: Create symbolic link to spark-env.sh
  sudo: true
  file:
    src: "{{ spark_install_dir }}/spark/conf/spark-env.sh"
    dest: "/etc/profile.d/spark-env.sh"
    state: link
  tags:
    - spark

- name: Setup Spark log4j properties file
  sudo: true
  template:
    src: "log4j.properties.j2"
    dest: "{{ spark_install_dir }}/{{ item }}/conf/log4j.properties"
    mode: 0775
  with_items: spark_packages
  tags:
    - spark
