---
- name: Install Java package
  sudo: true
  yum:
    name: java-1.8.0-openjdk
    state: present
  tags:
    - spark

- name: Create Spark directory
  sudo: true
  file:
    path: "{{ spark_install_dir }}"
    state: directory
  tags:
    - spark

- name: Download Spark binaries
  sudo: true 
  get_url: 
    url: "http://mirror.ox.ac.uk/sites/rsync.apache.org/spark/spark-{{ item.split('-')[1] }}/{{ item }}.tgz"
    dest: "{{ spark_install_dir }}/{{ item }}.tgz"
  with_items: spark_packages
  tags:
    - spark 

- include: client.yml
