---
- name: Get the local username
  local_action: command whoami
  register: local_username

- name: Spread authorization key
  sudo_user: hdfs
  sudo: true
  authorized_key:
    user: hdfs
    key: "{{ lookup('file', '/tmp/id_rsa.pub.%s' % local_username.stdout) }}"
    state: present
  tags:
    - hdfs

- name: Create Hadoop HDFS data node directories
  sudo: true
  file: 
    path: "/dfs/dn"
    owner: hdfs
    group: hdfs
    state: directory
  tags:
    - hdfs

- name: Restart Hadoop HDFS data node
  sudo: true
  sudo_user: hdfs
  shell: source /etc/profile.d/hadoop.sh; hadoop-daemon.sh stop datanode; hadoop-daemon.sh start datanode
  tags:
    - hdfs
