---
- name: Create Hadoop HDFS name node directories
  sudo: true
  file:
    path: "/dfs/nn"
    owner: hdfs
    group: hdfs
    state: directory
  register: created_hdfs_namenode_data_dir
  tags:
    - hdfs

- name: Format HDFS name node data directories
  sudo_user: hdfs
  sudo: true
  shell: source /etc/profile.d/hadoop.sh; hdfs namenode -format
  when: created_hdfs_namenode_data_dir|changed
  tags:
    - hdfs

- name: Restart Hadoop HDFS name node
  sudo: true
  sudo_user: hdfs
  shell: source /etc/profile.d/hadoop.sh; hadoop-daemon.sh stop namenode; hadoop-daemon.sh start namenode
  tags:
    - hdfs

- name: Setup initial directories on HDFS
  run_once: true
  sudo_user: hdfs
  sudo: true
  shell: source /etc/profile.d/hadoop.sh; if ! hdfs dfs -test -d /tmp; then hdfs dfs -mkdir /tmp; fi; hdfs dfs -chmod 777 /tmp; if ! hdfs dfs -test -d /user; then hdfs dfs -mkdir -p /user; fi; if ! hdfs dfs -test -d /apps; then hdfs dfs -mkdir -p /apps; fi; if ! hdfs dfs -test -d /logs; then hdfs dfs -mkdir -p /logs; fi
  tags:
    - hdfs

- name: Create home directory for centos user on HDFS
  run_once: true
  sudo_user: hdfs
  sudo: true
  shell: source /etc/profile.d/hadoop.sh; if ! hdfs dfs -test -d /user/centos; then hdfs dfs -mkdir -p /user/centos; fi; hdfs dfs -chown centos /user/centos
  tags:
    - hdfs

- name: Create home directories for other users on HDFS
  run_once: true
  sudo_user: hdfs
  sudo: true
  shell: source /etc/profile.d/hadoop.sh; if ! hdfs dfs -test -d /user/{{ item.name }}; then hdfs dfs -mkdir -p /user/{{ item.name }}; fi; hdfs dfs -chown {{ item.name }} /user/{{ item.name }}
  when: item.enabled is defined and item.enabled == 1
  with_items: users
  tags:
    - hdfs
