- name: Install general packages
  sudo: true
  ignore_errors: true
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - java-1.8.0-openjdk
    - maven
    - gcc
    - gcc-c++
    - perl
    - ruby
    - git
    - emacs
    - nano
    - vim
    - screen
    - bzip2
    - ncompress
    - unzip
    - wget
    - tmux
    - zsh

# p7zip
- name: p7zip repository package
  sudo: true
  ignore_errors: true
  yum:
    name: http://packages.sw.be/rpmforge-release/rpmforge-release-0.5.2-2.el6.rf.i686.rpm
    state: present

- name: Install p7zip package
  sudo: true
  ignore_errors: true
  yum:
    name: p7zip
    state: present

# RAR
- name: Install RAR package
  sudo: true
  ignore_errors: true
  yum:
    name: http://pkgs.repoforge.org/rar/rar-3.8.0-1.el6.rf.x86_64.rpm
    state: present

# Python 3.3
- name: Install Software collection utilities package (for Python 3.3)
  sudo: true
  ignore_errors: true
  yum:
    name: scl-utils
    state: present

- name: Install Python 3.3 collection repository package
  sudo: true
  ignore_errors: true
  yum:
    name: https://www.softwarecollections.org/en/scls/rhscl/python33/epel-7-x86_64/download/rhscl-python33-epel-7-x86_64.noarch.rpm
    state: present

- name: Install Python 3.3 package
  sudo: true
  yum:
    name: python33
    state: present

- name: Install Pip package
  sudo: true
  ignore_errors: true
  shell: "scl enable python33 \"bash -c 'easy_install pip'\""

# Scala
- name: Install Scala package
  sudo: true
  ignore_errors: true
  yum:
    name: http://downloads.typesafe.com/scala/2.11.6/scala-2.11.6.rpm
    state: present

- name: Install SBT package
  sudo: true
  ignore_errors: true
  yum:
    name: http://repo.scala-sbt.org/scalasbt/sbt-native-packages/org/scala-sbt/sbt/0.13.1/sbt.rpm
    state: present

# fetch2hdfs.sh
- name: Put fetch2hdfs.sh
  sudo: true
  template:
    src: "fetch2hdfs.sh"
    dest: "/usr/sbin/fetch2hdfs.sh"
    mode: 0775
